name: Fetch and Organize Streams

# 触发条件
on:
  schedule:
    # 每天 UTC 时间 00:00 和 12:00 运行
    - cron: '0 0,12 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  fetch_streams:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出项目仓库
    - name: Checkout repository
      uses: actions/checkout@v3  # 确保 checkout 使用最新版本

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4  # 使用最新版本的 Python 设置
      with:
        python-version: '3.x'

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    # 4. 运行 Python 脚本
    - name: Run script
      run: |
        python fetch_streams.py

    # 5. 配置 Git 信息
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # 6. 提交并推送文件到项目仓库
    - name: Commit and Push changes
      run: |
        git add final_streams.txt
        git commit -m "Update final_streams.txt with new streams"
        git push origin HEAD:main  # 如果你使用的分支不是 main，请修改为你的分支

    # 7. 上传输出文件作为 GitHub Action 的工件 (artifact)，如果还需要保存工件
    - name: Upload streams file
      uses: actions/upload-artifact@v3  # 使用 v3 版本
      with:
        name: final_streams
        path: final_streams.txt
