name: Fetch and Organize Streams

# 触发的条件
on:
  schedule:
    # 每天 UTC 时间的 00:00 运行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch_streams:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出项目仓库
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    # 4. 运行 Python 脚本
    - name: Run script
      run: |
        python <your_script_name>.py

    # 5. 上传输出文件作为 GitHub Action 的工件 (artifact)
    - name: Upload streams file
      uses: actions/upload-artifact@v2
      with:
        name: final_streams
        path: final_streams.txt
